trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: pipeline-group-prod
  - group: pipline-group-common

extends:
  template: satan-template-pipeline.yml
  parameters:
      TAG: 'prod-'
      branchName: 'prod'